// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZicEY0MEecEn0BYiHjXsJLQu-Y1ni87g',
    appId: '1:890212341343:web:ffde72bb513a89dff66dea',
    messagingSenderId: '890212341343',
    projectId: 'wherewroks',
    authDomain: 'wherewroks.firebaseapp.com',
    storageBucket: 'wherewroks.firebasestorage.app',
    measurementId: 'G-BR79HL170Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc02ClUJzHzkC0dYJOofXmWNI3gftaHYQ',
    appId: '1:890212341343:android:f36234e6a07ded8ef66dea',
    messagingSenderId: '890212341343',
    projectId: 'wherewroks',
    storageBucket: 'wherewroks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuDlfjtLKcm6sd3ImJDa7VRgum5Pzgteg',
    appId: '1:890212341343:ios:12b1963d540bfe19f66dea',
    messagingSenderId: '890212341343',
    projectId: 'wherewroks',
    storageBucket: 'wherewroks.firebasestorage.app',
    iosBundleId: 'com.example.whereworks',
  );
}
